# Generated by Django 5.0.1 on 2024-01-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='Пароль')),
            ],
        ),
    ]
