# Generated by Django 5.0.1 on 2024-02-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogmodel',
            options={'ordering': ('id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
