# Generated by Django 5.0.1 on 2024-02-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalogmodel_options_catalogmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Фотография'),
        ),
    ]
